entryPoints:
  traefik:
    address: ":8081"
  http:
    address: ":3000"

api:
  insecure: true
  dashboard: true
  debug: true

log:
  level: info

accessLog:
  filePath: /Users/pud/Documents/repo/sandbox/moleculer-scale/scripts/access.log

providers:
  file:
    watch: true
    directory: "/Users/pud/Documents/repo/sandbox/moleculer-scale/scripts/conf"

